# fuzzel.ini — generated by the Omarchy theme system.
# Do not edit; edit ~/.config/omarchy/themed/fuzzel.ini.tpl instead.
# Rendered to ~/.local/state/omarchy/current/theme/fuzzel.ini on every theme change.

font=monospace:size=11
line-height=22
lines=14
width=72
horizontal-pad=20
vertical-pad=16
inner-pad=10

[colors]
background={{ background_strip }}f5
text={{ foreground_strip }}ff
prompt={{ accent_strip }}ff
placeholder={{ dark_foreground_strip }}ff
input={{ bright_foreground_strip }}ff
match={{ accent_strip }}ff
selection={{ lighter_background_strip }}ff
selection-text={{ bright_foreground_strip }}ff
selection-match={{ accent_strip }}ff
counter={{ dark_foreground_strip }}ff
border={{ accent_strip }}ff

[border]
width=2
radius=10
